version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false -a /home/irisowner/irisdev/init_openapisuite.sh
    environment:
      - CONVERTER_URL=http://swagger-converter
      - CONVERTER_PORT=8080
      - VALIDATOR_URL=http://swagger-validator-v2
      - VALIDATOR_PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports: 
      - 1972
      - 52796:52773
      - 53773
    volumes:
      - ./:/home/irisowner/irisdev
  swagger-converter:
    image: swaggerapi/swagger-converter:latest
    restart: always
    # optional, openapi-suite don't need port exposed
    ports:
      - 8085:8080
  swagger-validator-v2:
    image: swaggerapi/swagger-validator-v2:latest
    restart: always
    # optional, openapi-suite don't need port exposed
    ports:
      - 8086:8080
  # ollama:
  #   image: ollama/ollama:latest
  #   environment:
  #     - MODEL=mistral
  #     - EMBEDDINGMODEL=mxbai-embed-large
  #   volumes:
  #     - ./ollama/:/root/.ollama
  #     # - /home/lscalese/git-data/test-iris-vector/ollama/:/root/.ollama
  #   ports:
  #     - 11434:11434
  #   entrypoint: ["sh", "/root/.ollama/entrypoint.sh"]
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  


#docker run -d -p 8085:8080 --name swagger-converter swaggerapi/swagger-converter:latest
#docker run -d -p 8086:8080 --name swagger-validator-v2 swaggerapi/swagger-validator-v2:latest